baseurl = "https://ukrainer-in-trier.github.io"
metaDataFormat = "yaml"
title = "Ukrainer In Trier"
theme = "blist"

DefaultContentLanguage = "uk"
DefaultContentLanguageInSubdir = true
[languages]
    [languages.uk]
        contentDir = "content/uk" #Ukrainian
        weight = 1
        languageName = "Український"
    [languages.uk.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- громадська платформа, створена заради розвитку та підтримки українського культурного простору у вимушеній еміграції."
        introSubtitle2 = "В час, коли війна роздерла на шматки безліч доль та сердець, берегти, примножувати та плекати рідне стало особливо важливо."
        introSubtitle3 = "Наша мета - об'єднати активних, творчих українців Трієра та найближчих міст і селищ, обмінятися культурним досвідом з місцевими жителями."
        introPhoto = "/1.webp"
        logo = "/logo.svg"

    [[languages.uk.menu.main]]
        name = "News"
        url = "/uk/blog"
        weight = 1

    [[languages.uk.menu.main]]
        name = "About"
        url = "/uk/about/"
        weight = 2

    [[languages.uk.menu.main]]
        name = "Tags"
        url = "/uk/tags"
        weight = 3

    [[languages.uk.menu.main]]
        name = "Top Post"
        url = "/uk/blog/emoji-support/"
        weight = 4

    [[languages.uk.menu.main]]
        name = "Free Birds"
        url = "/uk/free-birds/"
        weight = 5

    [[languages.uk.menu.main]]
        identifier = "Help"
        name = "Help"
        url = "/uk/help/help-me/"
        weight = 6

     [[languages.uk.menu.main]]
        name = "I need help"
        url = "/uk/help/need-help/"
        weight = 1   
        parent = "Help"
        
     [[languages.uk.menu.main]]
        name = "I want to help"
        url = "/uk/help/want-help/"
        weight = 2  
        parent = "Help"

    [[languages.uk.menu.main]]
        name = "Partners"
        url = "/uk/partners"
        weight = 7

    [languages.de]
        contentDir = "content/de" # Deutsch
        weight = 2
        languageName = "Deutsch"
        title = "Blist (mehrsprachig)"
        description = "Modernes Blog-Theme für Ihre Hugo-Site."
    [languages.de.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- громадська платформа, створена заради розвитку та підтримки українського культурного простору у вимушеній еміграції."
        introSubtitle2 = "В час, коли війна роздерла на шматки безліч доль та сердець, берегти, примножувати та плекати рідне стало особливо важливо."
        introSubtitle3 = "Наша мета - об'єднати активних, творчих українців Трієра та найближчих міст і селищ, обмінятися культурним досвідом з місцевими жителями."
        introPhoto = "/1.webp"
        logo = "/logo.svg"

    [[languages.de.menu.main]]
        name = "Nachrichten"
        url = "/de/blog"
        weight = 1

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "/de/about"
        weight = 2

    [[languages.de.menu.main]]
        name = "Tags"
        url = "/de/tags"
        weight = 3

    [[languages.de.menu.main]]
        name = "Freie Vögel"
       url = "/de/free-birds/"
        weight = 4

    [[languages.de.menu.main]]
        identifier = "hilfe"
        name = "Hilfe"
        url = "/de/help"
        weight = 6

    [[languages.de.menu.main]]
        name = "Ich brauche Hilfe"
        url = "/de/help/need-help/"
        weight = 1   
        parent = "hilfe"
        
     [[languages.de.menu.main]]
        name = "Ich möchte helfen"
        url = "/de/help/want-help/"
        weight = 2  
        parent = "hilfe"

    [[languages.de.menu.main]]
        name = "Partner"
        url = "/de/partners/"
        weight = 7

    [languages.en]
        contentDir = "content/en" #English
        weight = 3
        languageName = "English"
    [languages.en.params]
        introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
        introSubtitle = "- громадська платформа, створена заради розвитку та підтримки українського культурного простору у вимушеній еміграції."
        introSubtitle2 = "В час, коли війна роздерла на шматки безліч доль та сердець, берегти, примножувати та плекати рідне стало особливо важливо."
        introSubtitle3 = "Наша мета - об'єднати активних, творчих українців Трієра та найближчих міст і селищ, обмінятися культурним досвідом з місцевими жителями."
        introPhoto = "/1.webp"
        logo = "/logo.svg"

    [[languages.en.menu.main]]
        name = "News"
        url = "/en/blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "/en/tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Free birds"
        url = "/en/free-birds/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Help"
        url = "/en/help"
        weight = 6

        [[languages.en.menu.main]]
        name = "I need help"
        url = "/en/help/need-help/"
        weight = 1   
        parent = "Help"
        
     [[languages.en.menu.main]]
        name = "I want to help"
        url = "/en/help/want-help/"
        weight = 2  
        parent = "Help"

    [[languages.en.menu.main]]
        name = "Partners"
        url = "/en/partners/"
        weight = 7

    [languages.fr]
        contentDir = "content/fr" #French
        weight = 4
        languageName = "Français"

    [languages.fr.params]
      introTitle = "Ukrainer <span class='text-red-600'>in Trier</span>"
      introSubtitle = "- громадська платформа, створена заради розвитку та підтримки українського культурного простору у вимушеній еміграції."
      introSubtitle2 = "В час, коли війна роздерла на шматки безліч доль та сердець, берегти, примножувати та плекати рідне стало особливо важливо."
      introSubtitle3 = "Наша мета - об'єднати активних, творчих українців Трієра та найближчих міст і селищ, обмінятися культурним досвідом з місцевими жителями."
      introPhoto = "/1.webp"
      logo = "/logo.svg"

    [[languages.fr.menu.main]]
        name = "Nouvelles"
        url = "/blog"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos"
        url = "/about/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Tags"
        url = "/tags"
        weight = 3

    [[languages.fr.menu.main]]
        name = "Oiseaux Libres"
        url = "/fr/free-birds/"
        weight = 4

    [[languages.fr.menu.main]]
        identifier = "aider"
        name = "Aider"
        url = "/fr/help"
        weight = 6

    [[languages.fr.menu.main]]
        name = "J'ai besoin d'aide"
        url = "/fr/help/need-help/"
        weight = 1   
        parent = "aider"
        
     [[languages.fr.menu.main]]
        name = "Je veux aider"
        url = "/fr/help/want-help/"
        weight = 2  
        parent = "aider"

    [[languages.fr.menu.main]]
        name = "Les partenaires"
        url = "/fr/partners/"
        weight = 7

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Ukrainer in Trier · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow us"

  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"
  stackoverflow = "https://stackoverflow.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
