name: CI
on: 
  push:
    branches: actions
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.103.0"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: ukrainer-in-trier.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: ukrainer-in-trier
          user_email: <username@email.com>
          publish_branch: master
        #   cname: example.com
